/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.alex.photos.app

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue

class AppTest {
    @Test
    fun appHasAGreeting() {
//        val classUnderTest = Main()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
        assertTrue(true)
    }
}
